### ISSUE TITLE
Invalid type for key 'remote'

### ISSUE THREAD

**Issue by soykot2910** [feder-cr/linkedIn_auto_jobs_applier_with_AI#100]
(gpu) soykot@soykots-MacBook-Pro LinkedIn_AIHawk_automatic_job_application % python main.py --resume soykot-resume.pdf
Configuration error: Invalid type for key 'remote' in config file data_folder/config.yaml. Expected <class 'bool'>.

config.yml

```
remote: true

experienceLevel:
  internship: true
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: true
  internship: false
  other: false
  volunteer: true

date:
  all time: false
  month: true
  week: false
  24 hours: true

positions:
  - Software Engineer


locations:
  - USA

distance: 100

companyBlacklist:
  - Noir
  - Crossover

titleBlacklist:

```
