### ISSUE TITLE
Runtime error: Error running the bot: Experience.__init__() missing 1 required positional argument: 'skillsAcquired'

### ISSUE THREAD

**Issue by ralyodio** [feder-cr/linkedIn_auto_jobs_applier_with_AI#15]
```
personal_information:
  name: "Anthony"
  surname: "Ettinger"
  dateOfBirth: "11/20/1974"
  country: "United States"
  city: "Los Gatos"
  address: "16375 Bonnie Lane, Los Gatos, CA 95032"
  phonePrefix: "1"
  phone: "4086562473"
  email: "ettinger@gmail.com"
  github: "https://github.com/ralyodio"
  linkedin: "https://linkedin.com/in/chovy"

self_identification:
  gender: "Male"
  pronouns: "he/him"
  veteran: false
  disability: true/
  ethnicity: "White"

legal_authorization:
  euWorkAuthorization: false
  usWorkAuthorization: true
  requiresUsVisa: false
  legallyAllowedToWorkInUs: true
  requiresUsSponsorship: false
  requiresEuVisa: true
  legallyAllowedToWorkInEu: false
  requiresEuSponsorship: true

work_preferences:
  remoteWork: true
  inPersonWork: false
  openToRelocation: false
  willingToCompleteAssessments: false
  willingToUndergoDrugTests: true
  willingToUndergoBackgroundChecks: true

education_details:
  - degree: "Bachelor of Science Business Administration"
    university: "San Diego State University"
    gpa: "3.0"
    graduationYear: "1998"
    fieldOfStudy: "Business Administration"
    skillsAcquired:
      leadership: "1998"
      problemSolving: "1994"
      criticalThinking: "1995"
      adaptability: "1996"
      perfectionism: "1997"

experience_details:
  - position: "Engineering Lead, Commercial Solutions"
    company: "Tomahawk Edison Sciences Inc."
    employmentPeriod: "Apr 2024 - Present"
    location: "Remote, USA"
    industry: "Government"
    keyResponsibilities:
      responsibility1: "Spearheaded the development of a prototype for satellite tracking utilizing NASA's worldwind.js library"
      responsibility2: "Successfully built the initial version of Sentinel Desktop (satellite tracker) as a Tauri app in Node.js and Svelte"
    skillsAcquired:
      javascript: "20"
      linux: "20"
      css: "20"
  
  - position: "Co-founder, Chief Technology Officer"
    company: "Skatespot, Inc."
    employmentPeriod: "Apr 2021 - Present"
    location: "Remote, USA"
    industry: "Commercial"
    keyResponsibilities:
      responsibility1: "Spearheaded the development of the technology stack and architecture for Skatespot.com and its APIs"
      responsibility2: "Devised and executed strategic plans for the enhancement of overall technological infrastructure and performance using Deno and React Native with MongoDB running on Ubuntu"
    skillsAcquired:
      javascript: "20"
      linux: "20"
      css: "20"

  - position: "Founder, Independent Contractor"
    company: "Profullstack, Inc."
    employmentPeriod: "Mar 2018 - May 2024"
    location: "Remote, USA"
    industry: "Commercial"
    keyResponsibilities:
      responsibility1: "Consulted on JavaScript projects and REST related APIs with a focus on blockchain front-end development."
      responsibility2: "Co-founded and served as the CTO of avenasea.com, a corporate travel app."
      responsibility3: "Founded husko.money, an NFT and memecoin project on the Polygon mainnet."
      responsibility4: "Managed Docker instances with CI/CD for seamless deployment."
    skillsAcquired:
      javascript: "20"
      linux: "20"
      css: "20"

  - position: "Principal Engineer"
    company: "Prognos Health, Inc."
    employmentPeriod: "Mar 2021 - Jan 2022"
    location: "Remote, USA"
    industry: "Healthcare"
    keyResponsibilities:
      responsibility1: "Spearheaded the development of a cutting-edge underwriting user interface project, leveraging Svelte Kit and vanilla CSS."
      responsibility2: "Successfully built and deployed the underwriting user interface, ensuring seamless user experience and efficient functionality."
      responsibility3: "Utilized JavaScript, Node.js, HTML, CSS, and Svelte to create a robust and intuitive application."
      responsibility4: "Effectively collaborated with cross-functional teams to gather requirements, identify technical challenges, and deliver innovative solutions."
    skillsAcquired:
      javascript: "20"
      linux: "20"
      css: "20"

  - position: "Senior Software Engineer"
    company: "IBM"
    employmentPeriod: "Nov 2014 - Mar 2018"
    location: "Remote, USA"
    industry: "Enterprise"
    keyResponsibilities:
      responsibility1: "Developed and implemented features for API Connect Editor, contributing to the advancement of the platform."
      responsibility2: "Successfully created the base application for the rewrite, paving the way for improved functionality, clean code and a better developer experience."
      responsibility3: "Conducted thorough UI testing using protractor, karma, and chai, guaranteeing the quality and reliability of the application."
      responsibility4: "Proficiently utilized the ReactJS library for efficient development and provided seamless i18n and l10n implementation."
      responsibility5: "Possess expertise in JavaScript, React, Node.js, HTML, and Cascading Style Sheets (CSS) , effectively applying these skills to deliver exceptional results."
    skillsAcquired:
      javascript: "20"
      linux: "20"
      css: "20"
      
projects:
  project1: "Primate.js - open source polymorphic development platform https://primatejs.com"
  project2: "FastestEngineer - a premium SaaS boilerplate based on svelte and primatejs https://fastest.engineer"

availability:
  noticePeriod: "asap"

salary_expectations:
  salaryRangeUSD: "250,000 USD"

skills:
  problemSolving: "10"
  criticalThinking: "20"
  adaptability: "20"
  javascript: "20"
  linux: "20"
  css: "20"

languages:
  - language: "English"
    proficiency: "Native"
```
