### ISSUE TITLE
generated resumes are not customized to job posting

### ISSUE THREAD

**Issue by carolinesharpe** [feder-cr/linkedIn_auto_jobs_applier_with_AI#323]
any resumes generated by the script use the exact same wording/phrasing from plain text resume to fill new ones. they are not customized to the job posting. 

[CV_1045.pdf](https://github.com/user-attachments/files/16923214/CV_1045.pdf)
[CV_4695.pdf](https://github.com/user-attachments/files/16923215/CV_4695.pdf)
[CV_7301.pdf](https://github.com/user-attachments/files/16923216/CV_7301.pdf)
[CV_7196.pdf](https://github.com/user-attachments/files/16923217/CV_7196.pdf)
[CV_9148.pdf](https://github.com/user-attachments/files/16923218/CV_9148.pdf)

**Comment by carolinesharpe** [comment]
here is a sample of the copied source info:

```
      - responsibility_1: "Orchestrated the cohesive development and market-wide launch of an AI business management platform, providing website creation, book authoring, podcast generation sales and email copywriting, contacts management, and more."
      - responsibility_2: "Ran cross functional meetings across development, engineering, support, and marketing teams to ensure alignment and monitor project progress."
      - responsibility_3: "Leveraged Agile and Scrum methodologies for efficient project management."
      - responsibility_4: "Managed full project lifecycles, expanding product lineup, exploring new opportunities, and increasing revenue."
      - responsibility_5: "Collaborated with support and client success teams to gather user feedback for innovative features."
```

**Comment by carolinesharpe** [comment]
here is the entire plain text resume file
```

personal_information:
  name: "Caroline"
  surname: "Sharpe"
  date_of_birth: "08/7/1997"
  country: "USA"
  city: "San Francisco"
  address: "439 Greenwich Street"
  phone_prefix: "+1"
  phone: "6502248535"
  email: "carolinesharpe97@gmail.com"
  github: null
  linkedin: "https://www.linkedin.com/in/caroline-sharpe/"
  
education_details:
  - degree: "Bachelor's Degree"
    university: "Saint Mary's College of California"
    gpa: "3.2/4"
    graduation_year: "2021"
    field_of_study: "Sociology"
    exam:
      Information Theory and Inference: "A"
      Algorithm Analysis and Design: "B"
      Object-Oriented Languages and Programming: "A-"
      Linear Algebra and Numerical Analysis: "B"
      Database: "B-"

experience_details:
  - position: "Product Manager"
    company: "Autofunnel.ai"
    employment_period: "09/2023 - Present"
    location: "San Francisco, CA"
    industry: "AI Software"
    key_responsibilities:
      - responsibility_1: "Orchestrated the cohesive development and market-wide launch of an AI business management platform, providing website creation, book authoring, podcast generation sales and email copywriting, contacts management, and more."
      - responsibility_2: "Ran cross functional meetings across development, engineering, support, and marketing teams to ensure alignment and monitor project progress."
      - responsibility_3: "Leveraged Agile and Scrum methodologies for efficient project management."
      - responsibility_4: "Managed full project lifecycles, expanding product lineup, exploring new opportunities, and increasing revenue."
      - responsibility_5: "Collaborated with support and client success teams to gather user feedback for innovative features."
    skills_acquired:
      - "Executive Stakeholder Management: Strengthened ability to coordinate and align product strategy with executive priorities and company goals."
      - "Product Strategy Development: Enhanced skills in developing strategic roadmaps to drive product growth and user engagement."
      - "Cross-Functional Team Leadership: Built on collaboration skills by leading cross-functional teams across development, engineering, QA, support, and marketing."

  - position: "Project Manager"
    company: "Autofunnel.ai"
    employment_period: "10/2021 - 09/2023"
    location: "San Francisco, CA"
    industry: "Mobile Web Gaming"
    key_responsibilities:
      - responsibility_1: "Owned and operated the release and go-to-market strategy for games, game characters, in-universe land and exploration tools, and live user experiences."
      - responsibility_2: "Coordinated development with executive decisions, marketing plans, design operations, and reports from support team."
      - responsibility_3: "Created systems to organize company hierarchy and operations, managed change for multiple teams as the company grew."
      - responsibility_4: "Managed given Agile and waterfall methodologies for project delivery and monitoring."
    skills_acquired:
      - "Agile & Scrum Methodologies: Mastered the use of Agile and Scrum practices for effective project management and iterative development."
      - "Project Management: Advanced skills in managing complex projects, balancing priorities, and ensuring successful delivery."
      - "Change Management: Developed strategies for scaling operations and adapting processes to meet changing company needs."

  - position: "Operations Coordinator"
    company: "Grow Factor, LLC"
    employment_period: "05/2020 - 10/2021"
    location: "San Francisco, CA"
    industry: "Small Business Services"
    key_responsibilities:
      - responsibility_1: "Scaled the company from 2 to 15 employees and nurtured the client base from 50 to over 4,000 in 18 months."
      - responsibility_2: "Wrote and operated A/B test requirements, including creating mockups, working with developers, and making critical decisions to improve product features."
      - responsibility_3: "Spearheaded change management initiatives and optimized operational processes through automation and system implementations across development, support, and product teams."
      - responsibility_4: "Optimized operational processes through automation and system implementations for several teams, including development, support, & product."
    skills_acquired:
      - "Client Growth and Retention: Gained expertise in expanding the client base and maintaining strong client relationships."
      - "Quality Assurance (QA) and A/B Testing: Developed skills in creating and executing testing protocols to enhance product quality."
      - "Operational Efficiency: Learned to optimize workflows and implement automated solutions to improve team productivity and effectiveness."

projects:
  - name: "JobBot"
    description: "AI-driven tool to automate and personalize job applications on LinkedIn, gained over 3000 stars on GitHub, improving efficiency and reducing application time"
    link: "https://github.com/liam-murphy/jobbot"
  - name: "mqtt-packet-parser"
    description: "Developed a Node.js module for parsing MQTT packets, improved parsing efficiency by 40%"
    link: "https://github.com/liam-murphy/mqtt-packet-parser"

achievements:
  - name: "Bookle.ai App"
    description: "AI-generated books of up to 180 pages of any genre and in any style."
  - name: "Podcaster App"
    description: "AI-based software that writes a podcast script and generates a vocal track to accompany it, based on a brief description and title."
  - name: "Mech.com: Sky Docks"
    description: "Live web-based game with up to 8 players at once."
  - name: "Mech.com: Kalahari Depths"
    description: "Solo ore-mining Match3 minigame to encourage user interaction."

certifications:
  - ""

languages:
  - language: "English"
    proficiency: "Native"
  - language: "Spanish"
    proficiency: "Conversational"

interests:
  - "Full Product Lifecycle Management"
  - "Cross-functional Collaboration"
  - "Stakeholder & Client Management"
  - "AI/ML Technologies"
  - "Agile & Scrum Methodologies"
  - "In-depth QA and A/B Testing"

availability:
  notice_period: "immediately"

salary_expectations:
  salary_range_usd: "90,000"

self_identification:
  gender: "Female"
  pronouns: "She"
  veteran: "No"
  disability: "No"
  ethnicity: "white"

legal_authorization:
  eu_work_authorization: "No"
  us_work_authorization: "Yes"
  requires_us_visa: "No"
  requires_us_sponsorship: "No"
  requires_eu_visa: "Yes"
  legally_allowed_to_work_in_eu: "No"
  legally_allowed_to_work_in_us: "Yes"
  requires_eu_sponsorship: "Yes"

work_preferences:
  remote_work: "Yes"
  in_person_work: "Yes"
  open_to_relocation: "Yes"
  willing_to_complete_assessments: "Yes"
  willing_to_undergo_drug_tests: "Yes"
  willing_to_undergo_background_checks: "Yes"
```
