### ISSUE TITLE
Runtime error: Error running the bot: 'exam' 

### ISSUE THREAD

**Issue by rezabanitaba** [feder-cr/linkedIn_auto_jobs_applier_with_AI#402]
Hi

I get this when trying to run the main module

```
Runtime error: Error running the bot: 'exam'
Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration
```

Your help is appreciated.

**Comment by RohanBera** [comment]
Either your YAML format is wrong (verify at https://www.yamllint.com/), or you left the "exam" key blank. 
If you don't wanna add your courses, you can just remove the "exam" key from your YAML file.

**Comment by thomHayner** [comment]
@rezabanitaba @RohanBera I believe you need to remove it from the resume builder rather than just removing it from ```plain_text_resume.yaml```, I know that resume builder had some recent changes though...can you 100% confirm that removing it from the .yaml file will exclude it from resumes?

**Comment by rezabanitaba** [comment]
@thomHayner 
The resume builder seems to be an external module, so I don't see how it can be modified. 
@RohanBera 
All my yaml are in good syntax.
I did remove the key exam and did not just leave it blank when I got that error.
I just added the key and a value for it , just like the example , but still getting the same error.

**Comment by feder-cr** [comment]
@rezabanitaba share your plain text and join the telegram group, so we can discuss it more easily - > https://t.me/AIhawkCommunity

**Comment by RohanBera** [comment]
@thomHayner 
I just tried with the latest code, seems to be working without the exam key.

@rezabanitaba 
about your error
`Runtime error: Error running the bot: Education.__init__() got an unexpected keyword argument 'education_level'
`
I believe the key `education_level` was changed to `educationLevel`.

**Comment by RohanBera** [comment]
@thomHayner
I just tried using the latest code, and it seems to be working without the exam key.

my yaml file: 

```
education_details:
  - education_level: "Degree"
    institution: "University"
    field_of_study: "study "
    final_evaluation_grade: "4/4"
    start_date: "2022"
    year_of_completion: "2024"
  - education_level: "Degree"
    institution: "College"
    field_of_study: "Engineering"
    final_evaluation_grade: "4/4"
    start_date: "2017"
    year_of_completion: "2022"
```
