### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain_openai'

### ISSUE THREAD

**Issue by raja-prog** [feder-cr/linkedIn_auto_jobs_applier_with_AI#52]
Hi, This is the error I'm getting 
Configuration error: Experience level 'internship' must be a boolean value in config file data_folder/config.yaml.
Refer to the configuration guide for troubleshooting: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

but I'm using boolean in the same file internship key

**Comment by feder-cr** [comment]
@raja-prog sorry i dont understand your porblem

**Comment by arbaz686** [comment]
try `pip install langchain_openai` 

OR

the `internship` key in your config.yaml file is not being recognized as a boolean value. It might be due to incorrect formatting or spacing. 

   ```
   experienceLevel:
     internship: true
     entryLevel: false
     associate: false
     midSenior: false
   ```
